import { EventType, ExpoEvent } from './types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

export const EXPO_DATA: ExpoEvent[] = [
    // --- 嘉義大舞台 (Chiayi Grand Stage) ---
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【開幕大秀】《嘉義進行曲：時間列車》',
        type: EventType.Performance,
        dateDisplay: '12/12 (五) 19:30',
        dateSort: '2025-12-12T19:30',
        description: '演出團體｜廖士賢與阮劇團、築夢者街舞、躍演劇團、小事製作、悠巴歌謠傳唱隊、嘉義大學管樂團、鐵獅玉玲瓏、舒米恩、美秀集團、王彩樺。主持人｜許富凱、方宥心',
        tags: ['開幕大秀']
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【嘉常band換】《美好加一音樂節》',
        type: EventType.Performance,
        dateDisplay: '12/13 (六) 16:50',
        dateSort: '2025-12-13T16:50',
        description: '演出團體｜一種心情、裝咖人、青虫 ft. 王彙筑、落日飛車、盧廣仲',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【台語經典音樂會】《咱的歌・咱的聲》',
        type: EventType.Performance,
        dateDisplay: '12/14 (日) 18:30',
        dateSort: '2025-12-14T18:30',
        description: '演出者｜曾心梅、羅時豐、曹雅雯、羅文裕、蕭煌奇 ft. 李炳輝',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【金星製作舞台劇】《寶島一村》',
        type: EventType.Performance,
        dateDisplay: '12/17 (三) 17:30',
        dateSort: '2025-12-17T17:30',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【2025嘉義市國際管樂節】大型晚會及變換隊形表演',
        type: EventType.Performance,
        dateDisplay: '12/20 (六) 18:00',
        dateSort: '2025-12-20T18:00',
        description: '演出者｜翡翠騎士、熊本工業高等學校吹奏樂部、奈良學園大學行進樂部、范曉萱&100%樂團、黃宣YELLOW、景美女子高級中學樂儀旗隊、第一女子高級中學樂儀旗隊、建國高級中學樂旗隊、嘉義市管樂團 feat. 禾作社劇團、南興國民中學管樂旗藝術才能班、嘉頌重奏團、復雷閣動態藝術工作室',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【聲響派對】',
        type: EventType.Performance,
        dateDisplay: '12/21 (日) 18:30',
        dateSort: '2025-12-21T18:30',
        description: '演出團體｜朱宗慶打擊樂團、QMSO迷你交響樂團',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【扯鈴轉動老城光】《鈴能的挑戰》',
        type: EventType.Performance,
        dateDisplay: '12/24 (三) 19:10',
        dateSort: '2025-12-24T19:10',
        description: '演出團體｜世賢國小扯鈴隊、舞鈴劇團',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【霹靂魔幻音樂會】《樂武震天》',
        type: EventType.Performance,
        dateDisplay: '12/27 (六) 19:00',
        dateSort: '2025-12-27T19:00',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大舞台',
        locationDetail: '主舞台區',
        title: '【閉幕大典】《+1+1+1派對》',
        type: EventType.Performance,
        dateDisplay: '12/28 (日) 18:30',
        dateSort: '2025-12-28T18:30',
        description: '演出者｜李英宏 ft. 陳建瑋、國語作業簿',
        tags: ['閉幕大典']
    },

    // --- 市博願景館 ---
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '從產業遺構到公共願景：跨國際的再生對話',
        type: EventType.Forum,
        dateDisplay: '12/13 (六)',
        dateSort: '2025-12-13',
        description: '講者：\n許懷群處長 | 嘉義市政府都市發展處\n楊．可尼克 Jan Knikker | MVRDV 策略長\n廖慧昕 | MVRDV 設計總監',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '永續構築新可能：低碳設計與城市實踐',
        type: EventType.Forum,
        dateDisplay: '12/20 (六)',
        dateSort: '2025-12-20',
        description: '講者：\n陳正哲教授 | 南華大學藝術與設計學院院長\n楊．可尼克 Jan Knikker | MVRDV 策略長\n廖慧昕 | MVRDV 設計總監',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '永續對話與城市願景：展覽策展的轉譯與實踐',
        type: EventType.Lecture,
        dateDisplay: '12/14 (日)',
        dateSort: '2025-12-14',
        description: '講者：\n鄒蘅 | MVRDV 建築師',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '【木藝領航：從臺灣到世界的創意足跡】',
        type: EventType.Lecture,
        dateDisplay: '12/20 (六)',
        dateSort: '2025-12-20',
        description: '講者：\n莊嘉駿 | umami 設計師 ／共同創辦人\n郭良旗 | Tomood / 土與木之間 負責人',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '以木為語言：MVRDV 在嘉義市博的木築想像',
        type: EventType.Lecture,
        dateDisplay: '12/21 (日)',
        dateSort: '2025-12-21',
        description: '講者：\nVeronica Della Ventura | MVRDV 專案經理 / 建築師\n鄒蘅 | MVRDV 建築師',
        link: 'https://www.accupass.com/event/2511212052528642835440',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '木都再進化:臺灣木藝與生活對談',
        type: EventType.Lecture,
        dateDisplay: '12/21 (日)',
        dateSort: '2025-12-21',
        description: '講者：\n簡玉林 | 永興傢俱 Yung Shing Furniture 傢具設計師\n王淑燕 | 普田設計 Puten+ 創意總監',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '城市的微尺度：微型空間設計的翻轉',
        type: EventType.Lecture,
        dateDisplay: '12/27 (六)',
        dateSort: '2025-12-27',
        description: '講者：\nVeronica Della Ventura | MVRDV專案經理 / 建築師',
        link: 'https://linktr.ee/MVRDVCHIAYI',
        tags: ['自由入場']
    },
    {
        id: generateId(),
        venueGroup: '市博願景館',
        locationDetail: '嘉義市政府對面',
        title: '願景館工作坊',
        type: EventType.Workshop,
        dateDisplay: '多場次',
        dateSort: '2025-12-31', // Push to end
        isFull: true,
        link: 'https://linktr.ee/MVRDVCHIAYI',
    },

    // --- 市博共論館 ---
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '市民討論夜：新經濟抵嘉',
        type: EventType.Discussion,
        dateDisplay: '12/13 (六)',
        dateSort: '2025-12-13',
        link: 'https://forms.gle/K6EMbeyfKgU1n8y76',
        tags: ['需報名', '每場20人']
    },
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '市民討論夜：城市體驗抵嘉',
        type: EventType.Discussion,
        dateDisplay: '12/20 (六)',
        dateSort: '2025-12-20',
        link: 'https://forms.gle/K6EMbeyfKgU1n8y76',
        tags: ['需報名', '每場20人']
    },
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '市民討論夜：全齡人才抵嘉',
        type: EventType.Discussion,
        dateDisplay: '12/27 (六)',
        dateSort: '2025-12-27',
        link: 'https://forms.gle/K6EMbeyfKgU1n8y76',
        tags: ['需報名', '每場20人']
    },
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '主題導覽：天空散步',
        type: EventType.Tour,
        dateDisplay: '12/13, 12/14, 12/21',
        dateSort: '2025-12-13',
        link: 'https://forms.gle/Caioa8rs9uuRMMFZ7',
        tags: ['需報名', '每場20人']
    },
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '主題導覽：天空散步',
        type: EventType.Tour,
        dateDisplay: '12/27, 12/28',
        dateSort: '2025-12-27',
        link: 'https://forms.gle/Caioa8rs9uuRMMFZ7',
        tags: ['需報名', '每場20人']
    },
    {
        id: generateId(),
        venueGroup: '市博共論館',
        locationDetail: '嘉義市政府一樓中庭',
        title: '印記工作坊',
        type: EventType.Workshop,
        dateDisplay: '12/14 & 12/21',
        dateSort: '2025-12-14',
        link: 'https://forms.gle/QpNkvcPuZHRdcApv7',
    },

    // --- 嘉義市文化局音樂廳 ---
    {
        id: generateId(),
        venueGroup: '嘉義市文化局音樂廳',
        locationDetail: '音樂廳',
        title: '2025 嘉義市設計論壇 設計、社群與新連結',
        type: EventType.Forum,
        dateDisplay: '12/16 (一) 13:00',
        dateSort: '2025-12-16T13:00',
        link: 'https://eventgo.bnextmedia.com.tw/event/detail/e86300u692d3c37a918c',
    },

    // --- 嘉私選物 ---
    {
        id: generateId(),
        venueGroup: '嘉私選物',
        locationDetail: '嘉義舊監獄',
        title: '市集｜320＋1光陰的故事-時光市集',
        type: EventType.Market,
        dateDisplay: '12/13 (六)',
        dateSort: '2025-12-13',
        link: 'https://www.facebook.com/share/1ZsgEeVQ6S/',
    },
    {
        id: generateId(),
        venueGroup: '嘉私選物',
        locationDetail: '嘉義舊監獄',
        title: '走讀-嘉物事｜宜居裡的日常風景',
        type: EventType.Tour,
        dateDisplay: '12/21 & 12/27',
        dateSort: '2025-12-21',
        link: 'https://forms.gle/nrR17evSbsYrHbGk8',
    },
    {
        id: generateId(),
        venueGroup: '嘉私選物',
        locationDetail: '嘉義舊監獄',
        title: '嘉物事｜微觀凝視宜居之城',
        type: EventType.Lecture,
        dateDisplay: '12/20',
        dateSort: '2025-12-20',
        link: 'https://forms.gle/wrnEPSatb6PGirhf8',
    },
    {
        id: generateId(),
        venueGroup: '嘉私選物',
        locationDetail: '嘉義舊監獄',
        title: '嘉物事｜叢林中的沉默：從空地觀看都市中的野性',
        type: EventType.Lecture,
        dateDisplay: '12/28',
        dateSort: '2025-12-28',
        link: 'https://forms.gle/QyGG4w5rXu8WZ41MA',
    },

    // --- 嘉義顯影 ---
    {
        id: generateId(),
        venueGroup: '嘉義顯影',
        locationDetail: '火車站前及嘉義文化創意園區',
        title: '繪畫共創：車站時光寫生',
        type: EventType.Workshop,
        dateDisplay: '12/13',
        dateSort: '2025-12-13',
        link: 'https://reurl.cc/mklX4G',
    },
    {
        id: generateId(),
        venueGroup: '嘉義顯影',
        locationDetail: '火車站前及嘉義文化創意園區',
        title: '畫都顯影：掌心裡的城市切片',
        type: EventType.Workshop,
        dateDisplay: '12/20',
        dateSort: '2025-12-20',
        link: 'https://reurl.cc/LQNDLx',
    },

    // --- 相逢在庭前 ---
    {
        id: generateId(),
        venueGroup: '相逢在庭前',
        locationDetail: '嘉義市立美術館',
        title: '小小觀眾養成指南工作坊 (進階班)',
        type: EventType.Workshop,
        dateDisplay: '12/13',
        dateSort: '2025-12-13',
        isFull: true,
        link: 'https://reurl.cc/DOWrYR',
    },
    {
        id: generateId(),
        venueGroup: '相逢在庭前',
        locationDetail: '嘉義市立美術館',
        title: '小小觀眾養成指南工作坊 (初階班)',
        type: EventType.Workshop,
        dateDisplay: '12/14',
        dateSort: '2025-12-14',
        isFull: true,
        link: 'https://reurl.cc/x3zVeL',
    },
    {
        id: generateId(),
        venueGroup: '相逢在庭前',
        locationDetail: '林宅時敏堂',
        title: '琳瑯山閣下午茶歌',
        type: EventType.Other,
        dateDisplay: '12/27',
        dateSort: '2025-12-27',
        link: 'https://reurl.cc/lavXb6',
    },

    // --- CityWalk+1 ---
    {
        id: generateId(),
        venueGroup: 'CityWalk+1',
        locationDetail: '嘉義各地',
        title: '木造重混-木屋翻新了，然後呢？',
        type: EventType.Tour,
        dateDisplay: '12/12, 19, 26',
        dateSort: '2025-12-12',
        link: 'https://reurl.cc/3bOmmR',
        tags: ['平日場']
    },
    {
        id: generateId(),
        venueGroup: 'CityWalk+1',
        locationDetail: '嘉義各地',
        title: '嘉義城美事-傳統文化之美',
        type: EventType.Tour,
        dateDisplay: '12/16, 23',
        dateSort: '2025-12-16',
        isFull: true,
        link: 'https://reurl.cc/3bOmmR',
        tags: ['平日場']
    },
    {
        id: generateId(),
        venueGroup: 'CityWalk+1',
        locationDetail: '嘉義各地',
        title: '諧音梗走讀-嘉義招牌大搜密',
        type: EventType.Tour,
        dateDisplay: '12/17, 24',
        dateSort: '2025-12-17',
        link: 'https://reurl.cc/3bOmmR',
        tags: ['平日場']
    },
    {
        id: generateId(),
        venueGroup: 'CityWalk+1',
        locationDetail: '嘉義各地',
        title: '火雞散步團-東市場小菜文化',
        type: EventType.Tour,
        dateDisplay: '12/18, 25',
        dateSort: '2025-12-18',
        isFull: true,
        link: 'https://reurl.cc/3bOmmR',
        tags: ['平日場']
    },
    {
        id: generateId(),
        venueGroup: 'CityWalk+1',
        locationDetail: '嘉義各地',
        title: '靈感取樣所-咱嘉義變奏曲',
        type: EventType.Tour,
        dateDisplay: '12/13, 20, 27',
        dateSort: '2025-12-13',
        link: 'https://reurl.cc/AbdYVE',
        tags: ['週六場']
    },

    // --- 嘉義大教室 ---
    {
        id: generateId(),
        venueGroup: '嘉義大教室',
        locationDetail: '嘉義公園 & 西門交誼創新所',
        title: '工作坊｜生態系寫生',
        type: EventType.Workshop,
        dateDisplay: '12/20 & 12/28',
        dateSort: '2025-12-20',
        link: 'https://forms.gle/TUK9RcPpCdgN7Dr16',
    },
    {
        id: generateId(),
        venueGroup: '嘉義大教室',
        locationDetail: '嘉義公園 & 西門交誼創新所',
        title: '講座｜在路上遇到的學長姐們',
        type: EventType.Lecture,
        dateDisplay: '12/14',
        dateSort: '2025-12-14',
        link: 'https://forms.gle/qzXZG4sXtWUpMR9w8',
    },

    // --- 嘉義市政府北棟大樓預定地 ---
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/12 (五)',
        dateSort: '2025-12-12',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/13 (六)',
        dateSort: '2025-12-13',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/14 (日)',
        dateSort: '2025-12-14',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/17 (三)',
        dateSort: '2025-12-17',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/20 (六)',
        dateSort: '2025-12-20',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/21 (日)',
        dateSort: '2025-12-21',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/24 (三)',
        dateSort: '2025-12-24',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/27 (六)',
        dateSort: '2025-12-27',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義市政府北棟大樓預定地',
        locationDetail: '市集',
        title: '市集｜嘉義大市',
        type: EventType.Market,
        dateDisplay: '12/28 (日)',
        dateSort: '2025-12-28',
        link: 'https://www.facebook.com/share/p/17iuudTXB6/',
    },

    // --- 嘉義潮流節 ---
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: '潮流服飾轉印體驗',
        type: EventType.Exhibition,
        dateDisplay: '12/25-27',
        dateSort: '2025-12-25',
        link: 'https://www.facebook.com/share/p/1GnQ6NEhXv/',
    },

    // 12/26 DJ
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：Melting 99 b2b L-CC',
        type: EventType.Performance,
        dateDisplay: '12/26 (五) 17:00',
        dateSort: '2025-12-26T17:00',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：WUYO ft. BCW',
        type: EventType.Performance,
        dateDisplay: '12/26 (五) 18:10',
        dateSort: '2025-12-26T18:10',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：倍帝愛波 Betty Apple ft. Social Dis Dance',
        type: EventType.Performance,
        dateDisplay: '12/26 (五) 18:40',
        dateSort: '2025-12-26T18:40',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },

    // 12/27 DJ
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：FunkyMo',
        type: EventType.Performance,
        dateDisplay: '12/27 (六) 17:00',
        dateSort: '2025-12-27T17:00',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：王彙筑 ft. 白油 Bio',
        type: EventType.Performance,
        dateDisplay: '12/27 (六) 18:00',
        dateSort: '2025-12-27T18:00',
        description: '油水投影藝術家',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },
    {
        id: generateId(),
        venueGroup: '嘉義潮流節',
        locationDetail: '檜意森活村',
        title: 'DJ秀：someshiit 山姆 ft. 白油 Bio',
        type: EventType.Performance,
        dateDisplay: '12/27 (六) 18:50',
        dateSort: '2025-12-27T18:50',
        description: '油水投影藝術家',
        link: 'https://www.facebook.com/share/17ggLGz14v/',
    },

    // --- 在地店家市博專屬活動 ---
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '植到芋見泥',
        title: '泥塑新生X療癒綠循環—永續盆栽',
        type: EventType.Workshop,
        dateDisplay: '12/14',
        dateSort: '2025-12-14',
        link: 'https://line.me/ti/p/Z83wn6j467',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '植到芋見泥',
        title: '320+1泥塑新生聯名筆架',
        type: EventType.Workshop,
        dateDisplay: '12/27 & 12/28',
        dateSort: '2025-12-27',
        link: 'https://line.me/ti/p/Z83wn6j467',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '渼橘客新鮮果優格專賣店',
        title: '親子果醬DIY',
        type: EventType.Workshop,
        dateDisplay: '12/14',
        dateSort: '2025-12-14',
        link: 'https://reurl.cc/vK0gAo',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: 'NG金工育所',
        title: '山節生香（梅山意象）',
        type: EventType.Workshop,
        dateDisplay: '12/19',
        dateSort: '2025-12-19',
        description: '「節」為竹節，「香」為茶香；意象含蓄，如山霧中竹影隱現、氣息生香。\n' +
            '透過銅製竹節造型茶則的製作展演，展現金屬工藝的細膩與力量，\n' +
            '讓手作從隱密的工作室走向大眾視野。\n' +
            '\n' +
            '材質：紅銅、999純銀\n' +
            '技法：葉脈壓印技法\n' +
            '金工師：銀銀美戴指 Hank老師 （20年資歷）\n\n' +
            '📍 現場開放人數：15人\n' +
            '📡 同步於 Facebook 進行直播\n' +
            '詳情請追蹤 IG @next_georg_',
        link: 'https://www.facebook.com/share/p/1GsY6LdeGd/',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: 'NG金工育所',
        title: '雲海行光（阿里山意象）',
        type: EventType.Workshop,
        dateDisplay: '12/20',
        dateSort: '2025-12-20',
        description: '「雲海」與「行光」呼應列車穿越雲間的畫面，\n' +
            '作品以銀映光，動靜皆成詩。\n' +
            '以銀版手斬技法刻畫金屬的質感與職人手感，\n' +
            '讓觀眾近距離感受銀器誕生的節奏與光影流動。\n\n' +
            '材質：999純銀\n' +
            '技法：手斬\n' +
            '金工師：神農閣 王俊祺老師(新銳)\n\n' +
            '📍 現場開放人數：15人\n' +
            '📡 同步於 Facebook 進行直播\n' +
            '詳情請追蹤 IG @next_georg_',
        link: 'https://www.facebook.com/share/p/1GsY6LdeGd/',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '大醫生林檜意店',
        title: '手作苔球五感森體驗',
        type: EventType.Workshop,
        dateDisplay: '12/13 & 12/27',
        dateSort: '2025-12-13',
        link: 'https://www.instagram.com/iforest_official/',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '名香茗茶',
        title: '品茗茶款3系列',
        type: EventType.Exhibition,
        dateDisplay: '12/13-31',
        dateSort: '2025-12-13',
        link: 'https://reurl.cc/xKLE2L',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '米拉音樂海娜',
        title: '點點曼陀羅彩繪體驗課程',
        type: EventType.Workshop,
        dateDisplay: '12/13, 14, 21, 27, 28',
        dateSort: '2025-12-13',
        link: 'https://line.me/R/ti/g/JaU8MKRjZY',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '水族星球',
        title: '小小魚護師體驗',
        type: EventType.Workshop,
        dateDisplay: '12/27',
        dateSort: '2025-12-27',
        link: 'https://forms.gle/2YnkNMpcVFuK7LzY9',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '義興嘉釀',
        title: '嘉義醬香手作體驗',
        type: EventType.Workshop,
        dateDisplay: '12/16 & 12/23',
        dateSort: '2025-12-16',
        isFull: true,
        link: 'https://www.facebook.com/share/p/1GsY6LdeGd/',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '中華耳穴保健協會',
        title: '攜手傳承 中醫文化',
        type: EventType.Workshop,
        dateDisplay: '12/28',
        dateSort: '2025-12-28',
        link: 'https://reurl.cc/jm3g2n',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '蜜嗜甜點',
        title: '蜜嗜X桃喜的烘焙冒險',
        type: EventType.Workshop,
        dateDisplay: '12/21',
        dateSort: '2025-12-21',
        link: 'https://www.instagram.com/miss_ledessert/',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '棋而思圍棋',
        title: '嘉城桃喜 × 棋思共鳴',
        type: EventType.Workshop,
        dateDisplay: '12/23',
        dateSort: '2025-12-23',
        link: 'https://lin.ee/KgVNGEP',
    },
    {
        id: generateId(),
        venueGroup: '在地店家市博專屬活動',
        locationDetail: '嘉義城隍廟&茉莉手作坊',
        title: '月老良緣 × 文昌智慧 ​ 祈願提袋 DIY',
        type: EventType.Workshop,
        dateDisplay: '12/27',
        dateSort: '2025-12-27',
        link: 'https://lin.ee/7BgILjQ',
    },

    // --- Other ---
    {
        id: generateId(),
        venueGroup: '其他活動',
        locationDetail: '未指定',
        title: '記憶運轉中：林業嘉義的日常與再生',
        type: EventType.Other,
        dateDisplay: '12/28',
        dateSort: '2025-12-28',
        link: 'https://forms.gle/aQziTmtuYMErK9ei6',
    },
];